//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameNet.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Console
    {
        public int Id { get; set; }
        public decimal QuantityPriceController { get; set; }
        public decimal TimePriceController { get; set; }
        public string ConsoleType { get; set; }
    }
}
