//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameNet.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderItem
    {
        public int Id { get; set; }
        public int ConsoleId { get; set; }
        public int quantity { get; set; }
        public decimal cost { get; set; }
        public decimal amount { get; set; }
        public int ShopId { get; set; }
        public int CustomerId { get; set; }
        public string ShopName { get; set; }
        public int OrderId { get; set; }
    }
}
